# Generated by Django 5.1.1 on 2024-10-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmorCamisola', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='primeiroNome',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ultimoNome',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='telemovel',
            new_name='phone',
        ),
    ]
