# Generated by Django 5.1.2 on 2024-10-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmorCamisola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boots',
            name='size',
            field=models.DecimalField(choices=[(36, 36), (36.5, 36.5), (37, 37), (37.5, 37.5), (38, 38), (38.5, 38.5), (39, 39), (39.5, 39.5), (40, 40), (40.5, 40.5), (41, 41), (41.5, 41.5), (42, 42), (42.5, 42.5), (43, 43), (43.5, 43.5), (44, 44), (44.5, 44.5), (45, 45), (45.5, 45.5), (46, 46), (46.5, 46.5), (47, 47)], decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='jersey',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shorts',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=50),
        ),
        migrations.AlterField(
            model_name='socks',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=50),
        ),
    ]
